// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

#include "ui.h"

extern int led;

void TurnOn(lv_event_t * e)
{
	led = 1;
}

void TurnOff(lv_event_t * e)
{
	led = 0;
}
