// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

#include "ui.h"
#include "ui_helpers.h"

/*---------------------------------------------------------------
 * Generated UI object references
 * Share the screen and its dynamic widgets with application code.
 *--------------------------------------------------------------*/

// Objects that belong to the dashboard screen.
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_BackgroundImage;
lv_obj_t * ui_TempLabel;
lv_obj_t * ui_HumiLabel;
void ui_event_OnButton(lv_event_t * e);
lv_obj_t * ui_OnButton;
void ui_event_OffButton(lv_event_t * e);
lv_obj_t * ui_OffButton;
// CUSTOM VARIABLES

// Placeholder used by SquareLine for actions performed during startup.
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

/*---------------------------------------------------------------
 * Validate generated project settings
 * Prevent image colors from being interpreted with the wrong bit depth.
 *--------------------------------------------------------------*/
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

/*---------------------------------------------------------------
 * Forward button events
 * Invoke application callbacks only after a complete press-and-release.
 *--------------------------------------------------------------*/

/**
 * @brief Route a released On button event to TurnOn().
 * @param e LVGL event generated for ui_OnButton.
 * @return Nothing.
 * @note Registered as the On button callback in ui_Screen1_screen_init().
 */
void ui_event_OnButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        TurnOn(e);
    }
}

/**
 * @brief Route a released Off button event to TurnOff().
 * @param e LVGL event generated for ui_OffButton.
 * @return Nothing.
 * @note Registered as the Off button callback in ui_Screen1_screen_init().
 */
void ui_event_OffButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        TurnOff(e);
    }
}

/*---------------------------------------------------------------
 * Initialize the generated interface
 * Apply the theme, build the dashboard, and make it the active screen.
 *--------------------------------------------------------------*/

/**
 * @brief Create and display the complete SquareLine interface.
 * @param None.
 * @return Nothing.
 * @note Called once from the Arduino setup() after LVGL is configured.
 */
void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
