// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

/*---------------------------------------------------------------
 * Generated interface declarations
 * Expose dashboard objects, event adapters, images, and initialization.
 *--------------------------------------------------------------*/

#ifndef _BASIC_LVGL_7_5_UI_H
#define _BASIC_LVGL_7_5_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// Dashboard builder and objects accessed by the application at runtime.
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_BackgroundImage;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_HumiLabel;
void ui_event_OnButton(lv_event_t * e);
extern lv_obj_t * ui_OnButton;
void ui_event_OffButton(lv_event_t * e);
extern lv_obj_t * ui_OffButton;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// Compiled image resources used by the background and button styles.
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_on_png);    // assets/on.png
LV_IMG_DECLARE(ui_img_off_png);    // assets/off.png

/**
 * @brief Build and load the generated dashboard interface.
 * @param None.
 * @return Nothing.
 * @note Called from the Arduino setup() after LVGL display registration.
 */
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
