// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

/*---------------------------------------------------------------
 * Component customization hook
 * Reserved for user code associated with reusable SquareLine components.
 * This project does not define custom component behavior.
 *--------------------------------------------------------------*/
