// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

/*---------------------------------------------------------------
 * Dashboard command declarations
 * Connect generated button events to the application output state.
 *--------------------------------------------------------------*/

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Request the controlled output to turn on.
 * @param e LVGL event that triggered the command.
 * @return Nothing.
 * @note Called after the On button is released.
 */
void TurnOn(lv_event_t * e);

/**
 * @brief Request the controlled output to turn off.
 * @param e LVGL event that triggered the command.
 * @return Nothing.
 * @note Called after the Off button is released.
 */
void TurnOff(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
