// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

#include "ui_helpers.h"

/*---------------------------------------------------------------
 * Generated widget property adapters
 * Translate SquareLine property identifiers into LVGL API operations.
 *--------------------------------------------------------------*/

/** @brief Set a bar value with the requested animation mode.
 * @param target Bar to modify. @param id Generated property identifier.
 * @param val New value. @return Nothing. @note Called by generated UI actions. */
void _ui_bar_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BAR_PROPERTY_VALUE_WITH_ANIM) lv_bar_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_BAR_PROPERTY_VALUE) lv_bar_set_value(target, val, LV_ANIM_OFF);
}

/** @brief Set one basic geometry property on an LVGL object.
 * @param target Object to modify. @param id Geometry property identifier.
 * @param val New coordinate or size. @return Nothing. @note Called by generated UI actions. */
void _ui_basic_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BASIC_PROPERTY_POSITION_X) lv_obj_set_x(target, val);
    if(id == _UI_BASIC_PROPERTY_POSITION_Y) lv_obj_set_y(target, val);
    if(id == _UI_BASIC_PROPERTY_WIDTH) lv_obj_set_width(target, val);
    if(id == _UI_BASIC_PROPERTY_HEIGHT) lv_obj_set_height(target, val);
}

/** @brief Select one option in a dropdown widget.
 * @param target Dropdown to modify. @param id Generated property identifier.
 * @param val Option index. @return Nothing. @note Called by generated UI actions. */
void _ui_dropdown_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_DROPDOWN_PROPERTY_SELECTED) lv_dropdown_set_selected(target, val);
}

/** @brief Replace the source displayed by an image widget.
 * @param target Image to modify. @param id Generated property identifier.
 * @param val Address of the image descriptor. @return Nothing. @note Called by generated UI actions. */
void _ui_image_set_property(lv_obj_t * target, int id, uint8_t * val)
{
    if(id == _UI_IMAGE_PROPERTY_IMAGE) lv_image_set_src(target, val);
}

/** @brief Replace the text displayed by a label.
 * @param target Label to modify. @param id Generated property identifier.
 * @param val Null-terminated text. @return Nothing. @note Called by generated UI actions. */
void _ui_label_set_property(lv_obj_t * target, int id, const char * val)
{
    if(id == _UI_LABEL_PROPERTY_TEXT) lv_label_set_text(target, val);
}

/** @brief Select a roller item with the requested animation mode.
 * @param target Roller to modify. @param id Generated property identifier.
 * @param val Item index. @return Nothing. @note Called by generated UI actions. */
void _ui_roller_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM) lv_roller_set_selected(target, val, LV_ANIM_ON);
    if(id == _UI_ROLLER_PROPERTY_SELECTED) lv_roller_set_selected(target, val, LV_ANIM_OFF);
}

/** @brief Set a slider value with the requested animation mode.
 * @param target Slider to modify. @param id Generated property identifier.
 * @param val New value. @return Nothing. @note Called by generated UI actions. */
void _ui_slider_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM) lv_slider_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_SLIDER_PROPERTY_VALUE) lv_slider_set_value(target, val, LV_ANIM_OFF);
}

/*---------------------------------------------------------------
 * Generated screen and widget actions
 * Provide reusable behavior shared by SquareLine event definitions.
 *--------------------------------------------------------------*/

/** @brief Initialize a target screen if needed and load it with animation.
 * @param target Address of the screen reference. @param fademode Transition type.
 * @param spd Transition duration. @param delay Delay before transition.
 * @param target_init Screen builder. @return Nothing. @note Called by generated navigation events. */
void _ui_screen_change(lv_obj_t ** target, lv_screen_load_anim_t fademode, int spd, int delay,
                       void (*target_init)(void))
{
    if(*target == NULL)
        target_init();
    lv_screen_load_anim(*target, fademode, spd, delay, false);
}

/** @brief Delete a generated screen through its stored reference.
 * @param target Address of the screen reference. @return Nothing.
 * @note Called when generated navigation no longer needs a screen. */
void _ui_screen_delete(lv_obj_t ** target)
{
    if(*target == NULL) {
        lv_obj_delete(*target);
        target = NULL;
    }
}

/** @brief Add an offset to an arc and announce the value change.
 * @param target Arc to modify. @param val Signed offset.
 * @return Nothing. @note Called by generated UI actions. */
void _ui_arc_increment(lv_obj_t * target, int val)
{
    int old = lv_arc_get_value(target);
    lv_arc_set_value(target, old + val);
    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

/** @brief Add an offset to a bar value.
 * @param target Bar to modify. @param val Signed offset. @param anm Animation mode.
 * @return Nothing. @note Called by generated UI actions. */
void _ui_bar_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_bar_get_value(target);
    lv_bar_set_value(target, old + val, anm);
}

/** @brief Add an offset to a slider and announce the value change.
 * @param target Slider to modify. @param val Signed offset. @param anm Animation mode.
 * @return Nothing. @note Called by generated UI actions. */
void _ui_slider_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_slider_get_value(target);
    lv_slider_set_value(target, old + val, anm);
    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

/** @brief Connect an on-screen keyboard to a text area.
 * @param keyboard Keyboard object. @param textarea Text area receiving input.
 * @return Nothing. @note Called when generated forms change focus. */
void _ui_keyboard_set_target(lv_obj_t * keyboard, lv_obj_t * textarea)
{
    lv_keyboard_set_textarea(keyboard, textarea);
}

/** @brief Add, remove, or toggle an LVGL object flag.
 * @param target Object to modify. @param flag Flag mask. @param value Generated operation selector.
 * @return Nothing. @note Called by generated UI actions. */
void _ui_flag_modify(lv_obj_t * target, int32_t flag, int value)
{
    if(value == _UI_MODIFY_FLAG_TOGGLE) {
        if(lv_obj_has_flag(target, flag)) lv_obj_remove_flag(target, flag);
        else lv_obj_add_flag(target, flag);
    }
    else if(value == _UI_MODIFY_FLAG_ADD) lv_obj_add_flag(target, flag);
    else lv_obj_remove_flag(target, flag);
}

/** @brief Add, remove, or toggle an LVGL object state.
 * @param target Object to modify. @param state State mask. @param value Generated operation selector.
 * @return Nothing. @note Called by generated UI actions. */
void _ui_state_modify(lv_obj_t * target, int32_t state, int value)
{
    if(value == _UI_MODIFY_STATE_TOGGLE) {
        if(lv_obj_has_state(target, state)) lv_obj_remove_state(target, state);
        else lv_obj_add_state(target, state);
    }
    else if(value == _UI_MODIFY_STATE_ADD) lv_obj_add_state(target, state);
    else lv_obj_remove_state(target, state);
}

/** @brief Move a text-area cursor and retain keyboard focus.
 * @param target Text area to modify. @param val Generated direction selector.
 * @return Nothing. @note Called by generated keyboard actions. */
void _ui_textarea_move_cursor(lv_obj_t * target, int val)

{

    if(val == UI_MOVE_CURSOR_UP) lv_textarea_cursor_up(target);
    if(val == UI_MOVE_CURSOR_RIGHT) lv_textarea_cursor_right(target);
    if(val == UI_MOVE_CURSOR_DOWN) lv_textarea_cursor_down(target);
    if(val == UI_MOVE_CURSOR_LEFT) lv_textarea_cursor_left(target);
    lv_obj_add_state(target, LV_STATE_FOCUSED);
}

/** @brief Delete a screen after its unload event completes.
 * @param e Event containing the stored screen-reference address.
 * @return Nothing. @note Registered during generated animated navigation. */
void scr_unloaded_delete_cb(lv_event_t * e)

{

    lv_obj_t ** var = lv_event_get_user_data(e);
    lv_obj_delete(*var);
    (*var) = NULL;

}

/** @brief Apply a uniform opacity value to an object.
 * @param target Object to modify. @param val Opacity value.
 * @return Nothing. @note Called by generated UI actions and animations. */
void _ui_opacity_set(lv_obj_t * target, int val)
{
    lv_obj_set_style_opa(target, val, 0);
}

/*---------------------------------------------------------------
 * Generated animation adapters
 * Connect LVGL animation values to object geometry and appearance.
 *--------------------------------------------------------------*/

/** @brief Release animation data allocated for a generated action.
 * @param a Animation whose user data is no longer required.
 * @return Nothing. @note Called automatically when that animation completes. */
void _ui_anim_callback_free_user_data(lv_anim_t * a)
{
    lv_free(a->user_data);
    a->user_data = NULL;
}

/** @brief Apply an animation value to an object's x coordinate.
 * @param a Animation containing the target object. @param v New coordinate.
 * @return Nothing. @note Called for each x-position animation step. */
void _ui_anim_callback_set_x(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_x(usr->target, v);

}

/** @brief Apply an animation value to an object's y coordinate.
 * @param a Animation containing the target object. @param v New coordinate.
 * @return Nothing. @note Called for each y-position animation step. */
void _ui_anim_callback_set_y(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_y(usr->target, v);

}

/** @brief Apply an animation value to an object's width.
 * @param a Animation containing the target object. @param v New width.
 * @return Nothing. @note Called for each width animation step. */
void _ui_anim_callback_set_width(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_width(usr->target, v);

}

/** @brief Apply an animation value to an object's height.
 * @param a Animation containing the target object. @param v New height.
 * @return Nothing. @note Called for each height animation step. */
void _ui_anim_callback_set_height(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_height(usr->target, v);

}

/** @brief Apply an animation value to an object's opacity.
 * @param a Animation containing the target object. @param v New opacity.
 * @return Nothing. @note Called for each opacity animation step. */
void _ui_anim_callback_set_opacity(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_style_opa(usr->target, v, 0);

}

/** @brief Apply an animation value to image scale.
 * @param a Animation containing the target image. @param v New scale.
 * @return Nothing. @note Called for each image-scale animation step. */
void _ui_anim_callback_set_image_zoom(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_image_set_scale(usr->target, v);

}

/** @brief Apply an animation value to image rotation.
 * @param a Animation containing the target image. @param v New angle.
 * @return Nothing. @note Called for each image-rotation animation step. */
void _ui_anim_callback_set_image_angle(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_image_set_rotation(usr->target, v);

}

/** @brief Select an image-set frame from an animation value.
 * @param a Animation containing the image set. @param v Requested frame index.
 * @return Nothing. @note Called for each frame animation step. */
void _ui_anim_callback_set_image_frame(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    usr->val = v;

    if(v < 0) v = 0;
    if(v >= usr->imgset_size) v = usr->imgset_size - 1;
    lv_image_set_src(usr->target, usr->imgset[v]);
}

/** @brief Read the target object's aligned x coordinate.
 * @param a Animation containing the target object. @return Current x coordinate.
 * @note Called when an x animation determines its starting value. */
int32_t _ui_anim_callback_get_x(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_x_aligned(usr->target);

}

/** @brief Read the target object's aligned y coordinate.
 * @param a Animation containing the target object. @return Current y coordinate.
 * @note Called when a y animation determines its starting value. */
int32_t _ui_anim_callback_get_y(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_y_aligned(usr->target);

}

/** @brief Read the target object's current width.
 * @param a Animation containing the target object. @return Current width.
 * @note Called when a width animation determines its starting value. */
int32_t _ui_anim_callback_get_width(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_width(usr->target);

}

/** @brief Read the target object's current height.
 * @param a Animation containing the target object. @return Current height.
 * @note Called when a height animation determines its starting value. */
int32_t _ui_anim_callback_get_height(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_height(usr->target);

}

/** @brief Read the target object's current opacity.
 * @param a Animation containing the target object. @return Current opacity.
 * @note Called when an opacity animation determines its starting value. */
int32_t _ui_anim_callback_get_opacity(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_style_opa(usr->target, 0);

}

/** @brief Read the target image's current scale.
 * @param a Animation containing the target image. @return Current image scale.
 * @note Called when a scale animation determines its starting value. */
int32_t _ui_anim_callback_get_image_zoom(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_image_get_scale(usr->target);

}

/** @brief Read the target image's current rotation.
 * @param a Animation containing the target image. @return Current image angle.
 * @note Called when a rotation animation determines its starting value. */
int32_t _ui_anim_callback_get_image_angle(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_image_get_rotation(usr->target);

}

/** @brief Read the image-set frame stored for an animation.
 * @param a Animation containing the frame state. @return Current frame index.
 * @note Called when a frame animation determines its starting value. */
int32_t _ui_anim_callback_get_image_frame(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return usr->val;

}

/*---------------------------------------------------------------
 * Generated value-to-text helpers
 * Format widget state for labels and trigger dependent value events.
 *--------------------------------------------------------------*/

/** @brief Format an arc value between a prefix and postfix.
 * @param trg Label receiving text. @param src Arc providing the value.
 * @param prefix Leading text. @param postfix Trailing text. @return Nothing.
 * @note Called when a generated arc label is refreshed. */
void _ui_arc_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_arc_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}

/** @brief Format a slider value between a prefix and postfix.
 * @param trg Label receiving text. @param src Slider providing the value.
 * @param prefix Leading text. @param postfix Trailing text. @return Nothing.
 * @note Called when a generated slider label is refreshed. */
void _ui_slider_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_slider_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}

/** @brief Choose label text from another object's checked state.
 * @param trg Label receiving text. @param src Object providing state.
 * @param txt_on Checked text. @param txt_off Unchecked text. @return Nothing.
 * @note Called when a generated checked-state label is refreshed. */
void _ui_checked_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * txt_on, const char * txt_off)
{
    if(lv_obj_has_state(src, LV_STATE_CHECKED)) lv_label_set_text(trg, txt_on);
    else lv_label_set_text(trg, txt_off);
}

/** @brief Move a spinbox by one step and announce its new value.
 * @param target Spinbox to modify. @param val Sign selecting increment or decrement.
 * @return Nothing. @note Called by generated spinbox controls. */
void _ui_spinbox_step(lv_obj_t * target, int val)

{

    if(val > 0) lv_spinbox_increment(target);

    else lv_spinbox_decrement(target);


    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

/** @brief Select a generated theme when theme support is compiled in.
 * @param val Theme identifier. @return Nothing.
 * @note Called by generated theme-selection events. */
void _ui_switch_theme(int val)

{

#ifdef UI_THEME_ACTIVE
    ui_theme_set(val);
#endif
}


